In [3]:
import pandas as pd
import joblib

In [4]:
subs = pd.read_csv(r"subs_bal_test_predictions.csv")
bodieswS = pd.read_csv(r"bodieswS_bal_test_predictions.csv")
W2v = pd.read_csv(r"spacyW2v_bal_test_predictions.csv")

In [5]:
lr = joblib.load(r"Qbal_lr\bal_lr.sav")

In [6]:
df = pd.DataFrame({"subs": subs["pred_y"].tolist(), "bodieswS": bodieswS["pred_y"].tolist(), "W2v": W2v["pred_y"].tolist()})

In [7]:
X = df.to_numpy()
print(X[0:5])

[[0.48052195 0.09621675 0.53980164]
 [0.51025856 0.98378307 0.56349511]
 [0.26692441 0.34320322 0.47294487]
 [0.40504095 0.37116724 0.69072162]
 [0.43180564 0.83457643 0.59301484]]


In [8]:
sols = lr.predict_proba(X)[:,1]
print(sols[:5])

[0.01094408 0.62939482 0.030943   0.06394275 0.42612817]


In [9]:
solution = pd.DataFrame({"author": subs["author"].tolist(), "gender":sols})
print(solution.head())

           author    gender
0    --redbeard--  0.010944
1       -Allaina-  0.629395
2  -AllonsyAlonso  0.030943
3          -Beth-  0.063943
4        -Greeny-  0.426128


In [10]:
solution.to_csv(r"bal_lrSolution.csv", index = False)